### ISSUE TITLE
Error when training DANA model 

### ISSUE THREAD

**Issue by ksachdeva** [mmalekzadeh/dana#2]
Hi,

When I tried to train the DANA model using the notebook from the repo in Google colab; I get the following error

![dana-training](https://user-images.githubusercontent.com/127006/130709343-c832100b-68e9-42c0-9025-32588dae7f66.png)

I have tried to print the various shapes.

Note that in Google Colab, the Tensorflow version is now 2.6; most likely you used an older version to train. But indeed the shape of X does look a little strange.

I have not changed anything in your notebook (except for from_logits=False)

Regards & thanks
Kapil

**Comment by mmalekzadeh** [comment]
Many thanks for pointing out this.

I have updated the notebook and added this line for now.
`!pip install tensorflow==2.3.0`

Now it works well. I need to spend some time later to see what is the problem with TF 2.6.

Best
Mohammad

**Comment by ksachdeva** [comment]
Thanks @mmalekzadeh 

I tried with 2.3 and then 2.5 ....it worked for both.

I again tried with 2.6 and it is working now. Did you manage to fix it for 2.6 as well? (unfortunately, reviewing the changes in notebooks is not easy). 

Regards
Kapil

**Comment by mmalekzadeh** [comment]
Thanks for your great help. 
Didn't do anything to fix it for 2.6 yet. Happy if it works :-)
I fixed it to 2.3 to prevent future potential errors with newer versions.
